// Generated by CoffeeScript 1.6.3

(function() {
    // Переменные
    answers = '2022,гимназия,один,все,ответы,северная корона,большая медведица'
    music_file = 'snd/NLO.mp3'
    final_message = 'Скорее на финиш!!!'
    number_of_puzzles = 7
    
  var codes, delay, i, images, solved_codes, sound, word,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  codes = (function() {
    var _i, _len, _ref, _results;
    _ref = answers.split(',');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      word = _ref[_i];
      _results.push(word.split('').join(''));
    }
    return _results;
  })();

  images = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; _i <= number_of_puzzles; i = ++_i) {
      _results.push("img/" + i + ".jpg");
    }
    return _results;
  })();

  sound = new Audio(music_file);

  solved_codes = [];

  delay = function(m, f) {
    return setTimeout(f, m);
  };

  $(function() {
    var form, input, map, overlay, reload;
    form = $('form');
    input = $('input');
    overlay = $('img.overlay');
    map = $('img.map');
    reload = $('.reload');
    return form.on('submit', function() {
      var code;
      code = $.trim(input.val().toLowerCase());
      code = code.replace(/\s+/g, ' ');
      code = code.replace('a', 'а');
      if (__indexOf.call(codes, code) >= 0) {
        if (__indexOf.call(solved_codes, code) >= 0) {
          alert('Вы уже вводили этот код');
        } else {
          solved_codes.push(code);
          if (sound.paused) {
            sound.play();
            overlay.attr('src', map.attr('src'));
            overlay.removeClass('hidden');
          }
          delay(100, function() {
            map.attr('src', images[solved_codes.length]);
            overlay.addClass('hidden');
            return delay(4000, function() {
              reload.removeClass('hidden');
              if (codes.length === solved_codes.length) {
                return $('.interaction').html(final_message);
              }
            });
          });
        }
        return input.val('');
      } else {
        return alert('Нет, не ' + code);
      }
    });
  });

}).call(this);
